### ISSUE TITLE
Adding non-sample sampler to backend

### ISSUE THREAD

**Issue by hyunjimoon** [hyunjimoon/SBC#31]
Due to speed issues etc, I wish to extend `sample` function. Samplers that provide`draws` matrix can replace this function which include `variational`, `optimize`, and each of their `_mpi` correspondents which could assist in finding global optimal.

1. Is creating new function that substitute `sample` to `variational` from `SBC_fit.SBC_backend_cmdstan_sample` in [this](https://github.com/hyunjimoon/SBC/blob/0a188c292688778a357620df0fc6c40d8bc6debb/R/backends.R#L235) line suffice? I don't know what change is needed for`SBC_backend_cmdstan_sample ` function.

2. I wonder `optimize` function could be supported. Maybe stochastic optimization which produces sample-like output and is known to construct Markov chain could have potential. See https://arxiv.org/abs/2009.00666

(edit) 
- 1) construct `draws` matrix with `save_iteration` from [here](https://mc-stan.org/docs/2_27/cmdstan-guide/optimization.html) which provide trajectory solution leading to MLE implemented [here](https://github.com/hyunjimoon/SBC/blob/0a188c292688778a357620df0fc6c40d8bc6debb/R/backends.R#L252)

- 2) make functions in `results.R` and `backends.R` that uses can the above matrix such as [this](https://github.com/hyunjimoon/SBC/blob/0a188c292688778a357620df0fc6c40d8bc6debb/R/backends.R#L252) line from our package. 

- 3) Similarly, repeat 2 for `variational` function which is easier than `optimize` as it provides `draws` matrix.

**Comment by Dashadower** [comment]
Regarding 2, ADVI is what's being called when you call `model$optimize`. Stan's current variational inference algorithm(optimize) is called ADVI. If you're meaning RVI, then you would need to install cmdstan/cmdstanr build with RVI support.

**Comment by Dashadower** [comment]
Scratch that - you are right optimizer and variationa are different. Either way, I think should be able to use both optimizer or VI as the backend.

**Comment by martinmodrak** [comment]
I likely won't be able to attend to this sooner than late next week, but if you want to add something like `SBC_backend_cmdstan_variational`, it should be relatively straightforward. You'll need to understand the basics of S3 classes (https://adv-r.hadley.nz/s3.html), otherwise the implementation makes little sense :-)

The minimal set of stuff you need to implement is:

- A "constructor" for the backend - can be very similar to the `SBC_backend_cmdstan_sample` function, just change class and which params are unacceptable
- An implementation of `SBC_fit` (basically jast a wrapper to call `$variational` on the model, once again can mostly copy `SBC_fit.SBC_backend_cmdstan_sample`
- An implementation of `SBC_fit_to_draws_matrix.CmdStanVB` (`CmdStanVB` is the class of the result of `$variational`), once again very simple, just call `$draws()` on the fit

Optionally, you can also provide `SBC_fit_to_diagnostics.CmdStanVB` to extract additional diagnostic information (time taken, whether ELBO converged, ...), but that's not needed for succesful use.

**Comment by Dashadower** [comment]
Working on it, PR should be up within this weekend

**Comment by hyunjimoon** [comment]
I started a `nonHMC` branch for adding two functions. Like we've discussed, whether `compute_results` should be implemented separately for each of them ($sample, $optimize, $variational) remains to be seen. I used [this](https://github.com/hyunjimoon/SBC-approx-sensitivity/blob/master/sbc-approx/twoParamBins.Rmd#L28) for the test code, but simply changing the function name would suffice. 
```
Dataset 1 resulted in error when post-processing the fit.
Calling `recompute_statistics` after you've found and fixed the problem could let you move further without refitting
Error: 'thin' must be smaller than the total number of iterations.``` was error log.

**Comment by hyunjimoon** [comment]
Issue #38, #39 are related.

**Comment by hyunjimoon** [comment]
The following explanation here: https://mc-stan.org/cmdstanr/reference/fit-method-draws.html is helpful.

Depends on the value of format. The defaults are:
- For MCMC, a 3-D draws_array object (iteration x chain x variable).
- For standalone generated quantities, a 3-D draws_array object (iteration x chain x variable).
- For variational inference, a 2-D draws_matrix object (draw x variable). An additional variable lp_approx__ is also included, which is the log density of the variational approximation to the posterior evaluated at each of the draws.
- For optimization, a 1-row draws_matrix with one column per variable. These are not actually draws, just point estimates stored in the draws_matrix format. See $mle() to extract them as a numeric vector.
